// Code generated by "esc -o flowsnoop3.go -pkg ebpf3 -private c/flowsnoop3.o"; DO NOT EDIT.

package ebpf3

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/c/flowsnoop3.o": {
		name:    "flowsnoop3.o",
		local:   "c/flowsnoop3.o",
		size:    5816,
		modtime: 1610194797,
		compressed: `
H4sIAAAAAAAC/+xYTWhcVRQ+My+ZJDXN32RiDBjKJG3ToMO8mTAdg4ZQqUYNpAtrtaDPMZlOBye/b0gj
gdqNQVxI/QVBRCqiiEgQIS6EuHCRRRciXRRUyMJFkC6iCHYReHLv+abvvZN5MoXQ1TxIz/u+e37u/e55
9w59/fTkE+FQiCpPiP4lF7nP7aj7Po5/76MQbd7P3AaCpvv2HGVzK4w3r7FtChPtOY7TK5K/oWsSbUYY
55bOsF2c5HjUbTKI2ojosVQj84uoG2Ze5TleQ/zDA98wbib623Gcxe5WjRejh7UtGETNRDT1OMfFjHFa
+53orPGF5r354gHzidc4n7iez8eo36btOYNol1S9j7TOGwb7r47+zLpG+1jn0S3gfuDrDufhDbFHbzg8
/xB16ny9pCQuRrvv1HH2FB/j+g9w/UILUViNtxA96plv+3vuvHv0unnDNt9197fHo0PQ+tvfoX069Ggd
VjUudvE8Xh3m9RY7Oxj3/aJxb5O/f2IRnkcux3jfeCis+0vy3r7cchzHO2/lH6NnNG6kwr75ZgL2PVPj
vmf0el8M2Pfz9LJv33ccttuwNx1vP6yiDxaxr/boLe6Lbu6TQgPREYVjPRpPPYu8T6N/uuPCr1/4oe+6
U8IvIfy24XeM1x0bZv9G9p86Db/zN0Vftuu+9OozFqDvWI36jml9TfRTBv20g37Kop/+vMf91IF+epB1
eGvXqRr3mbuOXU+ejQbOo/Kp7/MsxchR4zXXbTugupEa6/JB/+sV5IFOH1T0qt8b9Xujfm/U7436vVG/
N+7i3lCjambqTKUhV8ewR9NafYYOwEe9N+AvRNV9njwzSUFPTsf+5Uj+sk5m0Lq49xrAJ8N+/gYxvyD4
D8F/L/go8nwq6s6Bzzb6+X+QZ0fk+Qn8kOHnv0KeiQY/nwL/puD/QJ4fBf8d+GYxnzXw64J/CfmPRPx8
HPyQ4D9HnqTQeTnE3S/138NXIfW/Dl7q/zZ4qX8r8kv9L4CX+t9CHqn/D+Cl/teQR+o/DF7q/xvySP2/
Bi/1vwxe6v8c8kv9+8BL/T+p6Cl0PkdEnfzlcd/Dvh9SvHuIDsJOgB8U/Br4CcGPgi8JPkvMXxX8CSLq
InexWawjqnljH5/0nCHq3qn0hcIDRHTVg1WNL8V4ZR8UPkpE2x6sbsrbYvxe1zsxNDB49NjxOCXK+ZUy
JZbypeJcYSlv21Setiqvis7fYfE2m1uw6UJp/pI9Nz+/YNmXiuXpi5QolZZnrdzMzJJdLJBllYrT+Tk7
7zqmE9OUsMtL5dwrlLBfm1V28tQp00o/omwS1rRMYBP4JMOT8AZMA6cyjNmalglsAqdH4D8Cf+AUsAls
VsYxzGgEcAQ4DZxOeRTIWKYHjVgmYk3EAqeAU8AmsGn6ciV9uZKom0TdJB3MM6dPzf3PeBfbb8X3LP9P
MYS/iIwPqCeOJf3b///is2KgWfipE6SlSp3nO9kuAB/COivxHbAPBdRfidRWvz+g/laV+o1V6qdRX+7B
eqv33gzW74WA+JnD1f3l/j2lYiedeSK64uWzXf71HgqIXxa/kSrPRdTfNdy4uCdfL+x/AQAA///XTNow
uBYAAA==
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
