// Code generated by "esc -o flowsnoop3.go -pkg ebpf3 -private c/flowsnoop3.o"; DO NOT EDIT.

package ebpf3

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/c/flowsnoop3.o": {
		name:    "flowsnoop3.o",
		local:   "c/flowsnoop3.o",
		size:    3816,
		modtime: 1610184296,
		compressed: `
H4sIAAAAAAAC/+xXT2gjVRj/TSb/jLq73STdbIQ9xEXXRUMm3Q1LUFgKrisE7MFl29N0msYYTJM0E9pq
wb/Uo/RS8OChqEePhXoQevHozUvRS/FUxEMtgh4KI++9bzIzXzIYsd76IP3m93vf9/2+7+W9vM4Hr9Ye
RDQN7tDwJzzkjVtPec/36e+T0HAwrbh9CqrnzxxhrabC1tKcslZN2oO04hM6cAnAK+WY4i3KE1H8FoDn
J4h/6dkFiVfTqsDVzNPSNqNAEsAbd5T/o+ibEvvjCyH6hQn1C1L/ddK/JO1jHTgRevoDuU77uvLfrJ6o
dUnn1TpVjwnfIPybo/Jck9iu/iFxVtcwJfPlEAfQSmeGOs6Z4LNKP6f0m0kgIuaTwMu+ei9/wvuOq34+
Jp76dtchrP/LHyFkHW5J3Lqq6njntuq3NXVF4fypxAdfenpnjuPk2GbbknsQyMWDfBaKsMh/ZF6LjI1L
JIBTx3H8uscCW0G9LO36GFT9m+8djdQr477y+j7y5dmPqjwin1j/R4jD+Re6P/coD9W9Q/bifF2cr4vz
9f+dLzErVjApLzmvr4ivx0l9njsHH/EcpY+G8T6vzdUQNiwZ+7vD+apMpqPH9sP3UPwJ478mvhQJ8p8S
v8v4H4nvMd3bpHvI/H8h/4d6kN8jfo7xO26dLH9ZU7uK9/Ud7Tbe1xfE877eJ5739QPxvK8C6fK+fiJ/
3tc3xPO+PnPrZPkfA5hSO0WOKNmMJvjEkL9J9i8o/ibj4+T/kPG/kn+b8feI32b8CwCuIjbUXaQ+0pLX
R/j7EW/PXwcw78PiF3XDh8UVt83m/2v8M/ns9LXc9QyKg8bGAMV+o93qNPsN28agbrqPgm4MWXpasXo2
3mp31+1Ot9sz7fXWoP42iu322oppLS/37VYTptlu1Rsdu+E5zhTrKNqD/sBaQtF+d0XY2uysYRr3hC2R
NcyKghWavUuzdxUuzyisrGEahA3CZZom5MKyr+KKafjQnQCqmKXAXInylCgPYYOwUcL5jI48vaPjKKXs
LDun/B1Eow+7fuhdZHREGZ7+h/hFVlyS+YkT98QYnflUME+K+nTjr5B9MUR/V59M/0aI/udj9GNj9GdI
f+Q7SPh/d8PXbyEkfi8x3p9/f+K/OL3mdAF86OcPU8F+UyHxa+wOdMe3pL/rO/8ZX74c2b8DAAD//wam
p4XoDgAA
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
