// Code generated by "esc -o flowsnoop1.go -pkg ebpf1 -private c/flowsnoop1.c"; DO NOT EDIT.

package ebpf1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/c/flowsnoop1.c": {
		name:    "flowsnoop1.c",
		local:   "c/flowsnoop1.c",
		size:    1874,
		modtime: 1584454744,
		compressed: `
H4sIAAAAAAAC/7RUUW/bNhB+nn7FtxYNJNc27TRIizk2kKbtGqCbjdR72gZCJimZkEIKJOU5aPPfB1Ky
E2nNXrb6Rb77Tnf36b6751KxsuYCF3VaSVJKVe9J5UzKxHi7iL4JO1Y9ickepIQjVrOi690wRiqjnfbu
6DkXmVQCn5ZXl58+Lj+vEcfTi4vTswQvMT19nUSRdaZmDkwrRe2XCKhfncIaRmU1ay1u3cGanges0sYd
bI8e7TcIxZkuZ9H9LHq7+kA/Xn9eL3++ufwl9jUEc1IrO0Sn7hDT81dvzpKZ7yd1kkGq0jfeRjlWbbnB
wBYb6jRtTJ/PukOILeimzrIQk0SeCCGolXXpphS4XF2PsRNGZncodR4K+KzU50kwWiCkNqmyngvdipQL
EyfjCDDC1UYh7vWSxLbYjBY+Ei8R/vffT2bR/ROMZIeQ/F/4yB4dJdxf2hT/RkY+yaX7cofJTksOrinT
tXLxt/qF77dbQlaYo0PXBwbRKCtzJTjYNjUYVAxzxD1ngkaAHdWEB+b4cu8hqRxKoZoqo0UpVPBmiOOK
/T75EyeY7LNJgh/nmOzPJj+QAa5XuzNoVd5hQCKE39eviGU1Whx07MPPcXKCvnP6OgEZ4Ld3K6SKY321
6iTx4Tbl3GA+f7R/LcL/ifh2cqWNQKlZWm61dQ8Jk/BshudpeebjYzfzTnNHvNniFg29HKFmpVuIH6Ce
wh17NLN25w5DOxbwcsfcvzNaWF0bJjpFHsNc2HAlCMF6+W75E9hWsKIZF09dSv34/HTGbYb2WIylYkbc
CuXCCRn6MSdtog/agItNnedS5Y1rU2U0nFlaGalcET97sccL/od6NkRQwrDzuRppr28ur96vlte/runq
Zvn2fayEG0IJJzNqBBNyJ+hR2YQgNbmFtMiMvgWxd5YUwihRktAM8fWlyonYCeUs8be6zbUnmTa3qXv4
3I83x0u/705CsdHCFpvDoB6Wrx1Hu9aTcHWfJkO52FHrUuPo/la6/8aml+z78/o7AAD//z4BZr9SBwAA
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
