// Code generated by "esc -o flowsnoop1.go -pkg ebpf1 -private c/flowsnoop1.c"; DO NOT EDIT.

package ebpf1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/c/flowsnoop1.c": {
		name:    "flowsnoop1.c",
		local:   "c/flowsnoop1.c",
		size:    3340,
		modtime: 1588016792,
		compressed: `
H4sIAAAAAAAC/9xWb2/ixhN+/fOnmJ8qRXYCGNrIPZUDiZC0jdo7UML1TRRZZnccVji77u7aJcrx3avx
H4IJ0EZ3Uqu+gp0ZzzzzzDNrfyMkSzKO8D6LUuEnQmYrP7U6YthZDJ29bsvSgz5xzJUHTadE6xvFlk3r
nDE/1coqMjvG6oxZYErK0Dw7ANl334LRLBRpvzpxY+tTLyh8qdK2PpN3c34HRWamkr6z7jsX0x/Dn69v
Z5OfbkYfXKqBzAolTQsadVtw8Wn8y9Xs1us3EAUVpHcVortecF/VKUFtDF8LWNBAFryCFlnBQMhESKwD
LUsXXMOpWc5Dq8LySDmNrUPMMpxncVzEeA615PuQSWOjeYIwml53IEct4idI1ENRgLKGlMeD9hCK1DqS
hvoJFxhx1K7XcQA02kxLcHeweK5ZzttDioQzKP7vPu/1nfWBjkSjIfFV+hE77Ui0fyi9PNaMONhL8+Gj
neRBs5fi/M90U0F5az8WuAqZyqQ9d/cgbhUhCUoPCHqTO5HCABpzpB6LjZBGPEjkwBaRhtOUwQDcHaMH
5do3drX4gQE8r8klYnDdlN117+EEuqu468H/B9BdnXe9//mncD3Nz0HJ5AlOfQdgQ0q7Rw9Tpk69lzAA
kbaHL2ta+cvNr7wm4lxvXOUdULl47SJI25lgMIAAPn+GXWPvew+ewT+F2XgKkeTw6XIKiyhHoDUxNeSd
1bJsi9Nq2WtStyBTChjQU+2hUZlmuBVQX011AEdTXFNrwMRgMcfXqbr7ExTmdUVJdYt1hGQaH1Ha4m5r
FfLov2iye0hhwVsUVum5qbFyv75QZcHflVmwkVlwWGY04cnl5AdgC2RLsAthWiAsCANSUUGtkRqSECUJ
sMig6ZSJ9glU4souSqXN0zhMtZpjqDHi7pZcW9ALWnCykax3KLyU8FY434RTzzsAKiG/sv53lRy8Wcr4
exYlbikto1mrUhk3ttRxpWL6KyhPrLQrBt0+iPeyD+LszCvAEftGsztxT0rjxt6J+9KzKd07BCNXgm9W
6uhGbdBhXsK6vPrtth7++MP01qOpVnwgh/kTnJw0RV5Hd0kIW28KqkJceX8VGxyKXTvO7GY0vppOrj/O
wunN5OLKlWhbINGKONTIUOQYkmSgemtG+sHQXsVaPYJvnoy/RC0x8TnOswefvnuFfPAxR2mNT9+nVa6V
Hyv9GFmaPjHCMa+/7fbwR7fIrtkrireHZjmv3wSzaXg5mo3CXyfj8OZqdBmOJx9vZy7HvAUyekRau0JL
L7MiJso8xXRoLjtT7h9hJeSYh8ZG2oarR2G/jJadZP9GgqBd/a8/YFQcG+JiL29/BgAA//9VJ1xyDA0A
AA==
`,
	},
}

var _escDirs = map[string][]os.FileInfo{}
